### ISSUE TITLE
Earthlab Tutorial

### ISSUE THREAD

**Issue by tyson-swetnam** [genophenoenvo/keys#3]
Complete these tutorials, and save code into `/code` directory 

https://www.earthdatascience.org/courses/use-data-open-source-python/intro-raster-data-python/raster-data-processing/subtract-rasters-in-python/

**Comment by eshaan-joshi** [comment]
I managed to go through chapters 2, 3, and 5, I read the code, synopsis, and did my best to understand what it was doing.
I had quite a bit of trouble with lesson 4, as the lidar files could not be found by my the notebook. I'm going to clear my head and try again after some time.
