### ISSUE TITLE
Download NEON Data to CyVerse

### ISSUE THREAD

**Issue by tyson-swetnam** [genophenoenvo/keys#5]
Using the RStudio Geospatial container, clone the NEON-Shiny-Browser into the running instance by using the RStudio Terminal.

``` 
git clone https://github.com/cyverse-gis/NEON-Shiny-Browser
```

Set the working directory of the RStudio to the location you downloaded the Shiny app

```
setwd('~/NEON-Shiny-Browser')
library("shiny")
runApp()
```

You can also create a `local_job.r` file and save these scripts into it, and use the "Jobs" option to run the app as a background process. Once the `local_job.r` script is running, it will give you the address and port number that it is active on. You can access the Shiny app by typing and copying the 4 digit PORT number `rstudioapi::viewer("https://localhost:PORT")`

**Comment by eshaan-joshi** [comment]
Almost finished with this, I can make the app in my browser without any issue.

**Comment by tyson-swetnam** [comment]
Next steps I'd like for you to do with the NEON Shiny Browser are to find and download the discrete lidar data, the orthophoto mosaic data, and the hyperspectral data for the Santa Rita Experimental Range (SRER). Download these to your Discovery Environment RStudio. Then, use iCommands to move the downloaded files to a new directory called `/iplant/home/ejoshie/NEON_Downloads`(or whatever your cyverse username is). 

You can create folders using the DE's data window. 

https://learning.cyverse.org/projects/discovery-environment-guide/en/latest/

You will have to do an iCommands `iput` execution in the Terminal in RStudio

https://learning.cyverse.org/projects/data_store_guide/en/latest/step2.html#upload-files-folders-from-local-computer-to-data-store

Your sample command should be something like:

`iput -KPbvrf /home/rstudio/NEON_Downloads /iplant/home/ejoshie/`
