### ISSUE TITLE
Read current literature on RGB and lidar based segmentation of trees

### ISSUE THREAD

**Issue by tyson-swetnam** [genophenoenvo/keys#6]
https://www.biorxiv.org/content/10.1101/532952v2.full
https://www.mdpi.com/2072-4292/11/11/1309

https://www.sciencedirect.com/science/article/pii/S157495412030011X

https://www.frontiersin.org/articles/10.3389/fpls.2018.00866/full

**Comment by eshaan-joshi** [comment]
Finished reading the articles and taking notes. Thank you!
