### ISSUE TITLE
File Formats and visualization

### ISSUE THREAD

**Issue by tyson-swetnam** [genophenoenvo/keys#7]
Orthomosaics
https://www.dronegenuity.com/orthomosaic-maps-explained/

GeoTiff
https://en.wikipedia.org/wiki/GeoTIFF

Cloud Optimized Geotiff
https://www.cogeo.org/

lidar point clouds:
LAS 
https://en.wikipedia.org/wiki/LAS_file_format

LAZ - compressed LAS
https://rapidlasso.com/laszip/

EPT - Entwine Point Tile - pyramid of lidar data
https://entwine.io/

Potree -- viewer for LAS and EPT
https://github.com/potree/potree/

CloudCompare
https://www.danielgm.net/cc/

**Comment by eshaan-joshi** [comment]
Finished reading all the articles I could find, and I took notes on all of them.
